/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Compaign__factory } from "./Compaign__factory";
export { CompaignFactory__factory } from "./CompaignFactory__factory";
