/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Compaign } from "./Compaign";
export type { CompaignFactory } from "./CompaignFactory";
export * as factories from "./factories";
export { Compaign__factory } from "./factories/Compaign__factory";
export { CompaignFactory__factory } from "./factories/CompaignFactory__factory";
